### ISSUE TITLE
Usage help - how to perform mutable operations in `client.time` closure

### ISSUE THREAD

**Issue by urjitbhatia** [markstory/rust-statsd#16]
Hi, I am pretty new to rust. Using this lib was super simple, thanks for the work!

I don't know how to do mutable calls in the `client.time` closure callable because it is set as `Fn` and not `FnOnce` or `FnMut`.

I get this error: `cannot assign to data in a captured outer variable in an `Fn` closure`

Here is a little example of what I am trying to do. Any guidance appreciated:

```rust
extern crate statsd;
use statsd::Client;

#[derive(Debug)]
pub struct Foo {
    num: u64,
}

fn main() {
    let mut foo_num = Foo{num: 10};
    println!("before: {:?}", foo_num);
    let client = Client::new("127.0.0.1:8125", "foo").unwrap();
    client.time("timethis", || {
        // Assume this is an expensive operation I want to time that takes ownership of a mutable ref
        foo_num.num+=1;
        println!("foo: {:?}", foo_num);
    });
}
```

**Comment by markstory** [comment]
@urjitbhatia I think the `time` method needs to be updated to accept `FnMut`. From the [FnMut](https://doc.rust-lang.org/std/ops/trait.FnMut.html) docs that should be a non-breaking change as `Fn` is a subtrait of `FnMut`.

**Comment by urjitbhatia** [comment]
Ah sounds good. I can submit a PR.

**Comment by urjitbhatia** [comment]
The more I think about this, the more it feels like it should be a `FnOnce` instead so that we can call things that consume from the outer scope. Thoughts?
Currently, even with `FnMut` I can't call something that consumes a variable from outer scope. It seems that the statsd client shouldn't force a smaller scope and let the caller manage it.

**Comment by markstory** [comment]
I'm ok with using FnOnce as well.
