### ISSUE TITLE
This library doesn't support IPv6

### ISSUE THREAD

**Issue by ghost** [markstory/rust-statsd#18]
IPv6 doesn't work because the UdpSocket is always bound to IPv4. `send_to` then always fails, but the error is silently ignored.

Took me quite a while to find this ...

This could be fixed by checking if the address is IPv6 or IPv4 and then binding to `0.0.0.0:0` for IPv4 and to `[::]:0` for IPv6.

**Comment by markstory** [comment]
Closing as a pull request is open now.

**Comment by ghost** [comment]
Can you please push the new version to crates.io?

**Comment by markstory** [comment]
Done. I thought I had done it last night, but the publish failed with an error.
