### ISSUE TITLE
Empty prefix results in `.` at the beginning of the metrics

### ISSUE THREAD

**Issue by ghost** [markstory/rust-statsd#21]
I'm not 100% sure but I think this isn't the intended behavior.

I'll make a pull request that fixes this.

**Comment by ghost** [comment]
#22

**Comment by markstory** [comment]
Closing as #22 has been merged.

**Comment by ghost** [comment]
Can you release a patch release on crates.io?

**Comment by markstory** [comment]
Yes. I will do that tonight.
